# Generated by Django 6.0.1 on 2026-02-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0007_moto_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="isinstance",
            field=models.IntegerField(default=1000, verbose_name="Цена"),
        ),
    ]
