# Generated by Django 6.0.1 on 2026-02-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0008_car_isinstance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="isinstance",
            new_name="amount",
        ),
    ]
