# Generated by Django 5.2.11 on 2026-02-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0009_rename_isinstance_car_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="amount",
        ),
        migrations.AddField(
            model_name="car",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="moto",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="car",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="milage",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="moto",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
